name: Auto deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to EC2
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@ec2-3-37-186-94.ap-northeast-2.compute.amazonaws.com 'cd ~/NHS-Backend-API && git pull && sudo lsof -t -i :1500 | xargs sudo kill -9 && screen -S server -X stuff "cd ~/NHS-Backend-API\n" && screen -S server -X stuff "python3 main.py\n"'